### PR TITLE
Disable server reset by default

### PR DESCRIPTION
**Pull request by irismessage**

### CODE REVIEW

**Comment by Davwyn** [comment]
This is set to true on purpose as not everyone is familiar with using server terminal controls. This allows players from in game to reset if they need a new game from losing or otherwise. If people want to change the setting they can do it themselves.

**Comment by irismessage** [comment]
In my opinion this is a massive ticking time bomb for anyone running a multiplayer server. It would be good if at least you could add a big warning if it's enabled

**Comment by Davwyn** [comment]
You are supposed to play the game with your friends. These are not designed to be dedicated public servers. If you plan on running a public server you should know better to always edit the server config file.

**Comment by Davwyn** [comment]
Put simply, this is the big problem. The sheer amount of players that will be upset because they play the game, lose, and can't figure out for the life of them how to start a new game will be massive. The in-game controls to reset the server won't work if this value is set to false.
If you know how to run a server AND plan to have people other than your friends on it, it's your responsibility like any server owner to change the config files before running any kind of public server. Case closed.

**Pull request closed without merging**
